In [1]:
import pandas as pd # pandas 모듈 호출

data_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data' 

df_data = pd.read_csv(data_url, sep='\s+', header = None) # csv 데이터 로드
df_data.columns = ['CRIM','ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO' ,'B', 'LSTAT'
, 'MEDV'] # 데이터의 열 이름 지정
df_data.head() # 데이터 출력

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [2]:
a = [1,2,3,4,5,6]

for i in a:
  print(i)

1
2
3
4
5
6


In [3]:
A = [[1,2,3],
     [4,5,6]]


In [4]:
A

[[1, 2, 3], [4, 5, 6]]

In [5]:
from typing import List

Matrix = List[List[float]]

In [6]:
Matrix

typing.List[typing.List[float]]

In [7]:
import numpy as np

np.eye(N=3, M=5, k=1) # 1칸 띄우고 시작하는 3행 5열의 단위행렬

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [8]:
a = np.array(range(10))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [10]:
a.reshape(-1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
a.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [12]:
a.reshape(-1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
a = a.reshape(5,2)

In [15]:
a.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(-5,5,2)

array([-5, -3, -1,  1,  3])

In [17]:
np.identity(8) # 단위행렬 생성.

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [18]:
np.diag(np.identity(8), k=1) # 대각선 값 추출, k는 지정해주면 (0,k) 부터 대각선 값 추출.

array([0., 0., 0., 0., 0., 0., 0.])

In [19]:
import random

np.random.uniform(0, 5, 10) # uniform()으로 0부터 5사이 값 10개 랜덤 가져오기

array([1.11853982, 0.99334258, 4.96089201, 2.09558897, 3.09821744,
       1.29993759, 1.43245746, 4.65284874, 2.26854035, 3.02192666])

In [20]:
np.random.normal(0,2,10) # normal()은 평균 0 분산 2인 값 10개

array([-1.01181413,  2.34243458,  2.35344253, -1.03753433,  0.1237898 ,
        1.90524182, -0.28611253, -1.305359  , -1.53838113, -0.33598015])

In [21]:
test_array = np.arange(1,13).reshape(3,4)
test_array.sum(axis=0)

array([15, 18, 21, 24])

In [22]:
test_array.mean() #평균

6.5

In [23]:
test_array.std() #표준편차

3.452052529534663

In [24]:
test_array.std(axis=0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [25]:
test_array > 5 # 비교연산은결과 T/F

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [26]:
np.where(test_array>5) # 결과 : 조건 만족하는 행 값 배열, 열 값 배열.

(array([1, 1, 1, 2, 2, 2, 2]), array([1, 2, 3, 0, 1, 2, 3]))

In [27]:
np.where(test_array>5, 10, 20) # 조건 만족하면 10 아니면 20

array([[20, 20, 20, 20],
       [20, 10, 10, 10],
       [10, 10, 10, 10]])

In [28]:
# np.argsort(), np.argmax(), np.argmin() 모두 인덱스를 결과로 반환

x = test_array
np.argsort(x)

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [29]:
np.argmax(x)

11

In [30]:
np.argmin(x)

0

In [31]:
x = np.array([4,6,7,3,2])
cond = x > 3
x[cond] # 조건을 만족하는 데이터만 반환

array([4, 6, 7])

In [32]:
x[cond].shape

(3,)

In [33]:
x.shape

(5,)

In [34]:
cond.shape

(5,)

In [35]:
cond = ([1,2,2,0,1,2]) # 팬시인덱스 : 인덱스 값을 직접 배열로 지정한 거
x[cond] # 인덱스 값 위치의 데이터 반환

array([6, 7, 7, 4, 6, 7])

In [36]:
x.take(cond) # ==x[cond]

array([6, 7, 7, 4, 6, 7])

In [37]:
x = np.array([[1,4], [9,16]], int)
a = np.array([0,1,1,1,0,0], int)
b = np.array([0,0,0,1,1,1], int)
x[a,b] # a 행 b 열의 값 추출

array([ 1,  9,  9, 16,  4,  4])